services:
  backend:
    container_name: backend-test
    build:
      context: ./backend
      target: test
    environment:
      - NODE_ENV=test
    env_file:
      - ./backend/.env.test
  database:
    container_name: database-test
    env_file:
      - ./backend/.env.test
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-adminpassword}
      POSTGRES_DB: ${DATABASE_NAME:-operations_erp_test}