services:
  backend:
    build:
      context: ./backend
      target: test
    environment:
      - NODE_ENV=test
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.test
  database:
    env_file:
      - ./backend/.env.test
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-adminpassword}
      POSTGRES_DB: ${DATABASE_NAME:-operations_erp_test}