services:
  frontend:
    build:
      target: production
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    ports:
      - "${PORT:-5173}:5173"
  backend:
    build:
      target: production
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    ports:
      - "${PORT:-80}:3000"
  database:
    env_file:
      - ./backend/.env.production
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-adminpassword}
      POSTGRES_DB: ${DATABASE_NAME:-operations_erp_prod}
  studio:
    env_file:
      - ./backend/.env.production
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-admin}:${DATABASE_PASSWORD:-adminpassword}@${DATABASE_HOST:-database}:${DATABASE_PORT:-5432}/${DATABASE_NAME:-operations_erp_prod}
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npx prisma studio --port 5555"